### ISSUE TITLE
weird logic in build.sh

### ISSUE THREAD

**Issue by tschuelia** [conda-forge/r-hmisc-feedstock#31]
### Comment:

Hi, I've noticed that in many (bioinformatics?) R recipes the `build.sh` contains this weird check of the target platform:
```
if [[ $target_platform =~ linux.* ]] || [[ $target_platform == win-32 ]] || [[ $target_platform == win-64 ]] || [[ $target_platform == osx-64 ]]; then
...
else
  mkdir -p $PREFIX/lib/R/library/Hmisc
  mv * $PREFIX/lib/R/library/Hmisc
  if [[ $target_platform == osx-64 ]]; then
  ....
``` 
This really does not make any sense to me since all this does is run the `mkdir` and `mv` as the following if is always false. 

I'm using this recipe as a proxy to ask whether someone can explain where this code comes from and if there is maybe a good reason for it that I'm missing :-) 
I also noticed that the Conda-forge migrator deleted that logic in the r-jpeg recipe (https://github.com/conda-forge/r-jpeg-feedstock/commit/268b4059609f0411c94a825854bc323803f659c9) and replaced it with the "standard":
```
export DISABLE_AUTOBREW=1

# shellcheck disable=SC2086
${R} CMD INSTALL --build . ${R_ARGS}
```

I'm happy to help cleanup the respective recipes if this can be replaced in other packages as well :-)

**Comment by mfansler** [comment]
This is old boilerplate from `conda-build` circa R 3.5. Things like OSX ARM migrator will automatically replace it, but if you see it causing a problem, feel free to replace it manually. Personally, I replace it if I'm editing a recipe, but don't go out of the way to update a build *just* to update this script.

**Comment by tschuelia** [comment]
Thanks for the clarification :) If I find some time I will do some cleanup, it will add some noise to the repos but I think it's worth removing the old code to prevent others from copy and pasting it in their recipes
